In [58]:
import numpy as np

In [59]:
# 1

# Python libraries are a collection of related modules that contain bundles of codes that can be used in different programs.
# Python Libraries are a set of useful functions that eliminate the need for writing codes from scratch.

In [60]:
# 2

# The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects.
#For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.

In [61]:
# 3

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f'Shape: {arr.shape}')
print(f'Size: {arr.size}')
print(f'Dimension: {arr.ndim}')

Shape: (3, 4)
Size: 12
Dimension: 2


In [62]:
# 4

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f'First Row: {arr[0]}')

First Row: [1 2 3 4]


In [63]:
# 5

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f'Element of 3rd row and 4th col is: {arr[2,3]}')

Element of 3rd row and 4th col is: 12


In [64]:
# 6

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.extract(arr%2 !=0 ,arr)

array([ 1,  3,  5,  7,  9, 11])

In [66]:
# 7

print('A random 3x3 matrix with values between 0 an 1: ',end="\n")
np.random.rand(3,3)

A random 3x3 matrix with values between 0 an 1: 


array([[0.45598391, 0.00613813, 0.47143674],
       [0.1735837 , 0.70653819, 0.78960094],
       [0.61500916, 0.50816111, 0.60714395]])

In [67]:
# 8

# randn generates samples from the normal distribution, while numpy.random.rand from a uniform distribution (in the range [0,1)).

In [68]:
np.random.rand(3,4)

array([[0.68858637, 0.11079245, 0.10567088, 0.54671644],
       [0.67192085, 0.52777297, 0.34728586, 0.63937849],
       [0.10575205, 0.95308747, 0.57687505, 0.52128848]])

In [69]:
np.random.randn(3,4)

array([[-0.04823425,  0.91779885,  0.71606172,  1.07390449],
       [ 1.5441682 ,  0.22690863,  0.97247007,  0.51511169],
       [ 1.73241419, -0.23502148,  0.61833521,  0.41814147]])

In [70]:
# 9

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.expand_dims(arr, axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [71]:
# 10

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [72]:
# 11

matA = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matB = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

print('Index wise multiplication',end='\n')
matA * matB

Index wise multiplication


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [73]:
print('Matrix multiplication',end='\n')
matA @ matB.T

Matrix multiplication


array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [74]:
print('Add both the matics',end='\n')
matA + matB

Add both the matics


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [75]:
print('Subtact matix B form A',end='\n')
matB - matA

Subtact matix B form A


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [76]:
print('Divide Matrix B by A',end='\n')
matB / matA

Divide Matrix B by A


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
# 12
# np.byteswap()

print(arr,end='\n')
print('\n')
print(arr.byteswap())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 72057594037927936 144115188075855872 216172782113783808
  288230376151711744]
 [360287970189639680 432345564227567616 504403158265495552
  576460752303423488]
 [648518346341351424 720575940379279360 792633534417207296
  864691128455135232]]


In [78]:
# 13

# The function numpy. linalg. inv() is available in the NumPy module and is used to compute the inverse matrix in Python.

arr4 = np.random.randint(1,10,(3,3))
arr4

array([[8, 8, 7],
       [2, 7, 5],
       [8, 9, 8]])

In [79]:
np.linalg.inv(arr4)

array([[ 0.78571429, -0.07142857, -0.64285714],
       [ 1.71428571,  0.57142857, -1.85714286],
       [-2.71428571, -0.57142857,  2.85714286]])

In [80]:
# 14

# The . reshape() function rearranges the data in an ndarray into a new shape.

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [82]:
# 15

# numpy.broadcast. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

arr1 = np.zeros((3,4))
arr2 = np.array([1,2,3,4])
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
arr2

array([1, 2, 3, 4])

In [84]:
arr1 + arr2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])